apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: com-att-idp
  labels:
    app: cart
    version: 1.0.0
spec:
  selector:
      matchLabels:
        app: cart
        version: 1.0.0
  replicas: 1
  template:
    metadata:
      labels:
        app: cart
        version: 1.0.0
    spec:
      containers:
        - name: cart
          image: com.att.idp/cart:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080