apiVersion: v1
kind: Service
metadata:
  name: "cart"
  namespace: "com-att-idp"
  labels:
    app: "cart"
    version: "1.0.0"
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: "cart"
    version: "1.0.0"